#!/usr/bin/env zsh
# screen window title set at exec command
# see [zsh-workers:13180]
# http://www.zsh.org/mla/workers/2000/msg03993.html
function set_screen_window_title() {
    emulate -L zsh
    local -a cmd
    cmd=($argv)
    case $cmd[1] in
        fg)
            if (( $#cmd == 1 )); then
                cmd=(builtin jobs -l %+)
            else
                cmd=(builtin jobs -l $cmd[2])
            fi
            ;;
        %*) 
            cmd=(builtin jobs -l $cmd[1])
            ;;
        cd)
            if (( $#cmd == 2)); then
                cmd[1]=$cmd[2]
            fi
            ;&
        ssh)
            if (( $#cmd == 2)); then
                cmd[1]=$cmd[2]
            fi
            ;&
        *)
            echo -n "k$cmd[1]:t\\"
            return
            ;;
    esac

    local -A jt; jt=(${(kv)jobtexts})

    $cmd >>(read num rest
    cmd=(${(z)${(e):-\$jt$num}})
    echo -n "k$cmd[1]:t\\") 2>/dev/null
}
