#!/usr/bin/env zsh

# sheet completion from http://blog.glidenote.com/blog/2012/04/16/sheet/
compdef _sheets sheet
function _sheets {
  local -a cmds
  _files -W ~/.sheets/ -P '~/.sheets/'

  cmds=('list' 'edit' 'copy')
  _describe -t commands "subcommand" cmds

  return 1;
}
