#!/usr/bin/env zsh
# Function For Screen
function ssh_on_screen() {
    if [ $WINDOW ]; then
        cd $HOME
        eval server=\${$#}
        TERM=xterm screen -t $server ssh "$@"
        cd -
    else
        TERM=xterm command ssh "$@"
    fi
}
