#!/usr/bin/env zsh
# Google Search
function google() {
    local str opt
    if [ $# != 0 ]; then 
        for i in $*; do
            str="$str+$i"
        done
        str=`echo $str | sed 's/^\+//'`
        opt='search?num=50&hl=ja&ie=utf-8&oe=utf-8&lr=lang_ja'
        opt="${opt}&q=${str}"
    fi
    w3m http://www.google.co.jp/$opt
    #firefox open http://www.google.co.jp/$opt
}
