#!/bin/bash
# .bash_profile

# keychain settings
HOST=`hostname`
KEYCHAIN=`which keychain`
IDENTITY=~/.ssh/id_rsa
SSH_AGENT=~/.keychain/$HOST-sh
$KEYCHAIN $IDENTITY
 . $SSH_AGENT

# User specific environment and startup programs
PATH=$HOME/bin:$PATH:/sbin:/usr/sbin
export PATH

# Network default settings
export http_proxy=
export HTTP_HOME=http://github.com/Tomohiro

case $TERM in
    linux) LANG=C ;;
    *) LANG=ja_JP.UTF-8 ;;
esac

# Replace bash to zsh

      if [ -f /usr/local/bin/zsh ]; then
          ZSH='/usr/local/bin/zsh'
      else
          ZSH=`which zsh`
      fi
      if [ $? = 0 ]; then
          case $TERM in
              xterm|xterm-256color|screen|screen-256color) exec $ZSH ;;
          esac
      fi
