#!/bin/sh
# Configuration file for tmux-powerline.

## General

    export TMUX_POWERLINE_DEBUG_MODE_ENABLED="false"
    export TMUX_POWERLINE_PATCHED_FONT_IN_USE="true"
    export TMUX_POWERLINE_THEME="default"
    export TMUX_POWERLINE_DIR_USER_THEMES="~/.tmux/themes"
    export TMUX_POWERLINE_DIR_USER_SEGMENTS="~/.tmux/segments"


## battery.sh

    export TMUX_POWERLINE_SEG_BATTERY_TYPE="percentage"
    export TMUX_POWERLINE_SEG_BATTERY_NUM_HEARTS="5"


## hostname.sh

    export TMUX_POWERLINE_SEG_HOSTNAME_FORMAT="short"


## tmux-powerline/segments/now_playing.sh

    export TMUX_POWERLINE_SEG_NOW_PLAYING_MAX_LEN="35"
    export TMUX_POWERLINE_SEG_NOW_PLAYING_TRIM_METHOD="trim"
    export TMUX_POWERLINE_SEG_NOW_PLAYING_ROLL_SPEED="1"
    export TMUX_POWERLINE_SEG_NOW_PLAYING_MUSIC_PLAYER="lastfm"
    export TMUX_POWERLINE_SEG_NOW_PLAYING_LASTFM_USERNAME="tomohiro-taira"
    export TMUX_POWERLINE_SEG_NOW_PLAYING_LASTFM_UPDATE_PERIOD="30"
    export TMUX_POWERLINE_SEG_NOW_PLAYING_NOTE_CHAR="$(emoji cd) "


## pwd.sh

    export TMUX_POWERLINE_SEG_PWD_MAX_LEN="30"


## weather.sh

    export TMUX_POWERLINE_SEG_WEATHER_DATA_PROVIDER="yahoo"
    export TMUX_POWERLINE_SEG_WEATHER_UNIT="c"
    export TMUX_POWERLINE_SEG_WEATHER_UPDATE_PERIOD="600"

    # Your location. Find a code that works for you:
    # 1. Go to Yahoo weather http://weather.yahoo.com/
    # 2. Find the weather for you location
    # 3. Copy the last numbers in that URL. e.g. "http://weather.yahoo.com/united-states/california/newport-beach-12796587/" has the numbers "12796587"
    export TMUX_POWERLINE_SEG_WEATHER_LOCATION="26320722"
